### ISSUE TITLE
saml and replay attack vulnerability

### ISSUE THREAD

**Issue by illpro** [IdentityPython/pysaml2#333]
I am new to SAML, so please excuse my ignorance or anything that I am misinformed about.

I have setup a SAML SP in my Django Project that talks to an Okta Chicklet (IDP) that I also setup. My Django App has two url endpints that we will call for brevity "login" and "sso". Login is responsible for preparing the authentication assertion that redirects the user to the configured idp's login form. Sso is responsible for verifying the idp's success response and logging the user into my web application.

All pretty clear and simple so far, right?

I've been successful in making a working version that logs me in, but there is one big issue that is bothering me. If I take the POST data for the sso endpoint that comes from the IDP, and "replay" it on another computer my SP thinks that the data is valid and logs the user into my web app. While the "replay attack" only works for a couple minutes, it still seems like a big enough security hole that I would like to fix it.

Most of my inspiration and code came from the Okta SP Example found [here](https://github.com/jpf/okta-pysaml2-example). I've included some parts of my pysaml2 implementation that I thought might be useful in understanding exactly what I am doing. If you need more, please just let me know and I can hopefully supply it.

Any help or advise on how to stop the replay attack, or why it isn't a viable attack in the wild, would be deeply appreciated. Thanks!

```
# Saml2Client config and setup
saml_settings = {
    'entityid': 'https://www.foobar.com/saml/sso/',
    'xmlsec_binary': '/usr/bin/xmlsec1',
    'metadata': {
        'remote': [{
            'url': 'https://okta.com/path/to/the/idp/config/metadata.xml,
            'cert': None,
        }],
    },
    'service': {
        'sp': {
            'endpoints': {
                'assertion_consumer_service': [
                    ('https://www.foobar.com/saml/sso/', BINDING_HTTP_REDIRECT),
                    ('https://www.foobar.com/saml/sso/', BINDING_HTTP_POST),
                ],
            },
            'allow_unsolicited': True,
            'authn_requests_signed': False,
            'want_assertions_signed': True,
        },
    },
}
sp_config = Saml2Config()
sp_config.load(saml_settings)
sp_config.allow_unknown_attributes = True
saml_client = Saml2Client(config=sp_config)
```

```
# SP auth assertion generation
req_id, info = saml_client.prepare_for_authenticate()
redirect_url = None
for key, value in info['headers']:
    if key is 'Location':
        redirect_url = value
response = redirect(redirect_url)
```

```
# IDP response validation
saml_response = request.POST.get('SAMLResponse')
authn_response = saml_client.parse_authn_request_response(saml_response, BINDING_HTTP_POST)
authn_response.get_identity()
user_info = authn_response.get_subject()
```

**Comment by macguru2000** [comment]
To add a little more detail to my concern, I guess I am worried that I am not implementing pysaml2 for best security. In particular I worry about these things:

1. Does my IDP response validation actually validate the data, or just parse it
1. What does `sp_config.allow_unknown_attributes = True` do and is it safe to use?
1. Is settings `authn_requests_signed` to `False` a good idea and does it have any security implications?
1. Is settings `allow_unsolicited` to `True` necessary for IDP initiated auth, and if so does it have any security implications?

**Comment by ganiserb** [comment]
I subscribe to @macguru2000 's questions.

**Comment by rohe** [comment]
Crystal clear description :-)

In answer to your questions
1) Yes!
2) I don't see any security problem with this. What it means is that if a response contains an attribute name that can not be found in the attribute map you are using.
3) This definitely has a security impact, since if the response is unsigned you have no way of knowing that what your looking at is what the IdP sent.
4) Yes, if allow_unsolicited is False IdP initiate auth is not allowed. 

My guess is that having allow_unsolicited=True is the cause of your 'problem'. 
If you allow IdP initiated auth then each 'response' has to be evaluated on it's own.
And as long as the response is correct then the SP should accept it.
Why it stops working after a while is because the response is timestamped and basically times out.
Each response contains an ID (which should be unique for each response) and pysaml2 doesn't check that it has seen the ID from the IdP before. Should be fairly easy to add such a check.

**Comment by rohe** [comment]
Hmm, you say that you sent the same response to another computer and that that SP instance just accepted the response.
I'd really like to see the response and also the metadata for both the SPs.
The SP should check that the destination of the response is itself. 
There are a number of cases where this might fail and I'd like know what's happening here.

**Comment by jkakavas** [comment]
The issue with `allow_unsolicited` is fixed with #430, and the rest of the questions are already answered. I will proceed to close this issue as resolved once #430 is merged

**Comment by quetzaluz** [comment]
This library is still vulnerable to replay attacks unless you implement rohe's suggestion mentioned previously in this thread:
>Each response contains an ID (which should be unique for each response) and pysaml2 doesn't check that it has seen the ID from the IdP before. Should be fairly easy to add such a check.

This "fix it yourself" approach seems to be justification for keeping this issue open since this repo does not offer configurable options for preventing these attacks; it is also appropriate that the vulnerability reported as open and unfixed here:
https://www.bountysource.com/issues/33925068-saml-and-replay-attack-vulnerability/backers

Other python saml libraries recommend the same fix as rohe, an example from onelogin:
https://github.com/onelogin/python-saml#replay-attacks

This issue should only be closed with a fix building the check rohe recommends, or by openly documenting the problem like onelogin does. This is a vulnerability anyone with basic software like Burp SAML Raider can discover and can potentially have very bad consequences for an application.

**Comment by quetzaluz** [comment]
Modifying response.py to delete assertions might resolve the replay vulnerbility; however, SAML tokens can still be intercepted and modified using tools like Burp SAML Raider.

**Comment by jkakavas** [comment]
I think this should be considered as a vulnerability of a SAML Service Provider implementation that uses pysaml2 , and not a vulnerability of the library itself. I have no objections on documenting this more clearly, but we don'c currently have any high level documentation on " how to build a production grade SAML SP with pysaml2" where this could fit

**Comment by peppelinux** [comment]
I have some doubts about the needs to manage this issue in the SP implementation, SP simply demands to pysaml2 the auth requests. If pysaml2 processes all the "exceedents" fake assertions as good, it will result as a hijacked response.

@jkakavas My question is about the SP implementation, and what you are told us: Is this means that to prevent this kind of attack it should be enough to configure signed requirements and other security canninesses in pysaml's SP configuration? If it is it I agree with you, otherwise it could sounds as a serious pysaml2 security flaws.

**Comment by c00kiemon5ter** [comment]
The library (`pysaml2`) cannot satisfy the requirement you'd like, as it would have to make a choice on the persistent mechanism that would be used (a certain database, a file on disk, etc) to store the requests.

What the library can do, is allow the user (the sp) to pass that information (as an argument), and have the library do the checks where needed. This offloads the responsibility of long-term storage (and across multiple processes/threads) to the user. The user can choose what storage mechanism to use and with what architecture and topology.

The two systems -the user and the library- should communicate this information through a well established data structure, where the user is the writer and the library is the reader.

This is currently implemented; though I believe the logic is a bit scattered. The name of the variable that represents that structure is `outstanding_queries`. The structure is a mapping (a dictionary) between session-IDs and `Request` objects (normally, originating from the SP). When a _response_ is received and if `allow_unsolicited` is set to `False`, the structure is checked for the session-ID (the entity-id) and if a matching `Request` object is _not found_ the response is considered to be _unsolicited_.

**Comment by peppelinux** [comment]
@c00kiemon5ter Thank you, this is the mix between library and implementation needed to understand a good SP configuration ready for production use.

**Comment by peppelinux** [comment]
Definitively I think that this topic was really interesting and @c00kiemon5ter placed an important emphasis on the correct implementation of pysaml2, however these aspects require a deep understanding of the inner workings of pysaml2 (bordering on debugging) and this certainly can discourage those hoping to find a ready-to-use solution to handle such sensitive security issues as everyone would like them to be, but without worrying too much about them (daily paradoxes).

In fact, nothing can be done except address persistence management each with his own storage mechanisms. I believe we can close this issue and consolidate the following one to keep the "scalable, production ready storage in terms of design" topic alive:
https://github.com/IdentityPython/pysaml2/issues/646

**Comment by peppelinux** [comment]
in djangosaml2 we have a session storage system that maps the identity cache, the session cookie would let a user to reuse an identity cache and then a saml response as a replay, but, If an attacker would steal the cookie ... who would care about the saml2 bearer, it would be already logged in with the cookie only!
Afaik I don't think that's threat. Hope to meet your thoughs
