### ISSUE TITLE
Does pysaml2 support Asynchronous SLO?

### ISSUE THREAD

**Issue by ddriddle** [IdentityPython/pysaml2#416]
I would like to know if it is possible to make an asynchronous SLO request using pysaml2. I have setup a pysaml2 SP that communicates with a Shibboleth IdP. I would like to make an asynchronous SLO logout request via HTTP_REDIRECT to the Shibboleth IDP using pysaml2. Is this possible using pysaml2? Can you point me to the functions I can use to implement this kind of logout?

**Comment by peppelinux** [comment]
Probably sp should accept unsolicited response, never implemented this kind of things cause I do not love unsolicited assertions... Would you like to tell us your use case,?

**Comment by peppelinux** [comment]
I think to have understand you problem, but the pending question means that probably it doens't interest you anymore.

btw I think that you would like to logout a user on your SP, indipendently from what the IdP will reply to you. That's right and you can do it before the SLO went out.

I think that if a user request a logout the SP must logout him, indipendently of what the IdP will do, because this latter is a third-party system that doesn't belong to SP responsability. If the IdP is faulty and the user won't be logged out from there put forceAuth=True to force everytime the SSO to the IdP.

If the IdP is faulty even with forceAuthn True... do not use it, contact the tech staff, this problem would be more great than a technical spec! :)
