### ISSUE TITLE
How to override Schemas / Classes

### ISSUE THREAD

**Issue by fmarco** [IdentityPython/pysaml2#527]
The main problem on using this (very nice) library on complex project is the following: 
How can classes inside modules `saml2.saml` and `saml2.samlp` be easily overridden?
In general, how can important classes / functions / settings be overridden by the eventual custom ones? 
 
## Code Version
4.5.0

## Expected Behavior
e.g.

```
CONFIG = {
...
'ovverride_saml': 'module_custom.saml_custom'
...
}
```

## Current Behavior
Very tricky to make customization.

**Comment by fmarco** [comment]
I see, thank you for the answer.
Well, as specific case consider:

1) having a subset of SAML2 schema (so, a restriction)
2) having a flow where insted of catching generic errors / exception among with their messages (step by step) from pysaml2 you need to collect them and show as a detailed error report.

If you need more clarifications or specific use cases let me know!

**Comment by peppelinux** [comment]
Ciao @fmarco 
I faced this kind of problem with a "from scratch" approach, see this as example. Probably it would help to follow how I faced this

https://github.com/peppelinux/Django-Identity/blob/master/djangosaml2_sp/djangosaml2_sp/djangosaml2_spid/views.py#L142

In nutshell we can even define own classes and rely on these instead of which standard, and hugher, pysaml2's methods does. 

BTW we have always to decide from time to time how to handle these cases.
I'm curious about you feedback on it, let us know, this thread will be closed in weeks otherwise.
A presto
