### ISSUE TITLE
Get URL from global_logout

### ISSUE THREAD

**Issue by davide-medina** [IdentityPython/pysaml2#677]
When I call the global_logout function, I parse the result and I get an html form POST with the correct data to redirect to Idp. Is it possible to get an URL directly?

## Code Version
5.0.0

## Expected Behavior
Get an URL to redirect the application to the Idp

## Current Behavior
I receive a form that I have to submit.

## Possible Solution
Return an url with the SLS of Idp and the SAMLRequest as parameter

## Steps to Reproduce
```
subject_id = name_id_from_string('name_id_string')
result = saml_client.global_logout(subject_id)
for entityid, logout_info in result.items():
    if isinstance(logout_info, tuple):
        binding, http_info = logout_info
        form = "".join(http_info["data"])
```

**Comment by peppelinux** [comment]
You just have to send your SLO Request (in saml2 format) to the related IdP service.
That's not a link.
If the IdP just have a weblink to handle that please do your customization to handle this shortcut but keep in mind that SAML2 does differently this.

Don't know If I understand well, otherwise This thread will be closed in weeks, thank you
