### ISSUE TITLE
documented `name_id_format` example for SP is part of IDP configuation

### ISSUE THREAD

**Issue by spaceone** [IdentityPython/pysaml2#710]
The `name-id-format` configuration is documented under the service provider configuration:
`Specific directives::sp::name_id_format`
https://pysaml2.readthedocs.io/en/latest/howto/config.html#name-id-format

But the example doesn't use a SP but a IDP key:
```
"service": {
    "idp": {
        "name_id_format": [
            "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
            "urn:oasis:names:tc:SAML:2.0:nameid-format:transient",
        ]
    }
}
```
Shouldn't it be?:
```
"service": {
    "sp": {
        "name_id_format": [
            "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
            "urn:oasis:names:tc:SAML:2.0:nameid-format:transient",
        ]
    }
}
```
Otherwise it should be moved to the `IDP` configuration options. Or is it valid for both?

**Comment by peppelinux** [comment]
It's valid for both @spaceone 

but thanks for the idea because an empirical verification is always a welcome opportunity. In fact I went to check production metadatas, configurations and operational examples to support this and I believe it is regular, indeed quite right in this way.

It is advisable to specify this characteristic on both sides, and in an identical way, both in SP and in IDP

**Comment by peppelinux** [comment]
You're right @spaceone, in IDP side that declaration would have been defined outside, as:
https://github.com/UniversitaDellaCalabria/uniAuth/blob/b93734eba00290a7efcf9a5e95a917cbe58bfd8e/django_idp/idp_pysaml2.py.example#L87

in SP side otherwise it's inside the sp key:
https://github.com/UniversitaDellaCalabria/uniTicket/blob/3308d17dfa498f6e5c2ebc8bd40afee89087240c/saml2_sp/settings.py.example#L26

@c00kiemon5ter Am I missing something?

**Comment by peppelinux** [comment]
my fault, I understand, that's the PR that fixes this:
https://github.com/IdentityPython/pysaml2/pull/715

thank you @spaceone, you're the best
