### ISSUE TITLE
Allow extending builtin attributemaps

### ISSUE THREAD

**Issue by klarose** [IdentityPython/pysaml2#726]
##  Code Version
6.1.0 (via the satosa:v7.0.1 container)

## Expected Behavior
It would be nice if I could extend the builtin saml attribute mappings with my extended mappings. We have per-customer mappings that need to be configured. However, we still want to use the "standard" ones provided by default.

## Current Behavior
I ended up having to configure attribute_map_dir to point to a directory with a custom python module mounted into
the container. The module uses python reflection (similar to the existing `ac_factory()` function) to load the defaults into itself,
then extend any that match the identifier with the desired values.

This seems pretty hackish, not only because it uses reflection, but because it depends on a few internals:
 - The structure of the map
 - The fact that the maps need to be global attributes of the module
 - The fact that only one map of a given identifier will be matched (this threw me for a brief loop).

I could have just hardcoded the builtin mappings, but I'd like to be able to take advantage of pysaml2 adding new ones in the future without needing to know about it.

## Possible Solution

If I could just point pysaml2 at a list of yaml files containing the maps in a well-documented format, rather than having to write
python code, I think it'd be very helpful. I also think that making the behaviour of whether to extend or overwrite the default mapping configurable would be helpful.

## Comments

This library, (as well as satosa) are fantastic! I've been able to get it running in my environment in just a few weeks, despite some fairly funky customisation. Thanks!

**Comment by spaceone** [comment]
I would like this, too.

**Comment by c00kiemon5ter** [comment]
Please, also have a read on #549 

The intention is to remove the maps altogether, because the way they work now is unstable. Attributes should be identified by their Name attribute, which provides an actual namespaced-name that along with the Format should be unambiguous within a deployment. 

I would like this work to happen soon, but time is limited. In the mean time, if you feel this is important, do provide a PR for this. The idea would be to load the bundled maps, then load the user maps, and if the Format matches, then extend the bundled mapping with the user-provided ones.

I will close this, but feel free to open a PR for this ;) 
Thanks!
