### ISSUE TITLE
In the IdP configuration file, how can I specify the SPs that my identity provider serves?

### ISSUE THREAD

**Issue by omizrahi99** [IdentityPython/pysaml2#761]
I am working off the example in `example/idp2`, and I can't find where I can specify the SPs that want to communicate with my IdP. Is there any way I can do this?

**Comment by c00kiemon5ter** [comment]
SPs and IdPs are autonomous entities. The basic thing that is needed to get them to communicate, is to exchange their metadata.

The SP knows about the IdP, because it is configured in a way that it consumes the IdP's metadata.
The IdP knows about the SP, because it is configured in a way that it consumes the SP's metadata.

pysaml2 provides the configuration option named `metadata` to configure how entities consume metadata, and thus how they get to know about other entities. You can read on the configuration option here: https://pysaml2.readthedocs.io/en/latest/howto/config.html#metadata

On the `example/idp2` code, the idp is configured to consume the metadata of the SP here:
https://github.com/IdentityPython/pysaml2/blob/6239655/example/idp2/idp_conf.py.example#L116-L118
The configuration is then passed to the `Server` class here:
https://github.com/IdentityPython/pysaml2/blob/6239655/example/idp2/idp.py#L1124

**Comment by omizrahi99** [comment]
I understand now... Thank you!

**Comment by omizrahi99** [comment]
@c00kiemon5ter What about the use case when the SP doesn't offer a metadata file? For example, if you try to set up Google Workspace as a SP, it only gives you their entityId (which doesn't seem to link to XML metadata) and an Assertion Consumer Service URL. See here: [https://support.google.com/a/answer/6349809?hl=en&ref_topic=7556907](url)

**Comment by c00kiemon5ter** [comment]
You still need to create a metadata file.
There are tools to help you with this, like: https://www.samltool.com/sp_metadata.php
