### ISSUE TITLE
Restriction on key data classes breaks signature verification

### ISSUE THREAD

**Issue by frcl** [IdentityPython/pysaml2#780]
The [restriction of key data to `raw-x509-cert`](https://github.com/IdentityPython/pysaml2/blob/c1fab71cf9f24dce4cc8985061c45a19481dcec0/src/saml2/sigver.py#L874) for xmlsec when verifing signatures causes failure if another class is used. Is there some reasoning behind this restriction?

## Code Version

```
$ pip show pysaml2
Name: pysaml2
Version: 6.5.1
Summary: Python implementation of SAML Version 2 Standard
Home-page: https://idpy.org
Author: IdentityPython
Author-email: discuss@idpy.org
License: Apache License Version 2.0
Location: /usr/local/lib/python3.8/site-packages
Requires: pyOpenSSL, defusedxml, six, pytz, cryptography, xmlschema, python-dateutil, requests, importlib-resources
```

```
$ xmlsec1 --version
xmlsec1 1.2.27 (openssl)
```

## Expected Behavior

Signature should be verified.

## Current Behavior

Verification fails with the following error:

```
error=func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=370:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
```

## Possible Solution

Removing the `--enabled-key-data` option fixes it for me.
I would expect an option to set allowed key data.

**Comment by c00kiemon5ter** [comment]
Hello,

> The restriction of key data to raw-x509-cert for xmlsec when verifing signatures causes failure if another class is used.

From my experience in the "SAML world" and industry x509 is the format (and thus key-data class) that is used to manage keys/certs; I haven't seen any system using anything else in practice. Other types of classes (as defined by xmldsig) are of course allowed by the SAML specs. Right now, the way this library is written, supports only x509. Bellow, I discuss some aspects (only what's related to the key-data class) of the signature verification process.

> Removing the `--enabled-key-data` option fixes it for me.

It looks like a fix. What happens in practice though is problematic.

Given what I wrote above (we only consider x509) to verify the signature of a SAML document we need to know the public-part of the key-pair that was used to sign the document. This is passed to xmlsec1 with the `--pubkey-cert-{type}` flag (where the type is usually `pem`), that is followed by the file that contains the certificate. We find this certificate by inspecting the metadata of the corresponding issuer (in this case, the IdP).

However, if we do not define a key-data class, then xmlsec1 will try all of them (ordered preference/precedence list: "key-name","key-value","retrieval-method","enc-key","aes","des","dsa","ecdsa","hmac","rsa","x509","raw-x509-cert"). This leads to security issues, as a man-in-middle can change the data within the SAML document and sign the document with another method (ie, using HMAC) and embed the key that was used for signing into the document. Taking HMAC as an example, xmlsec1 will get the public-part of the certificate through `--pubkey-cert-pem` but will ignore it, as it will find the HMAC key-data embedded in the SAML XML document (and it happens that the HMAC key-data class has higher precedence than x509). The signature verification will be successful, but in reality the document will have been tampered.

To correctly verify the document with xmlsec1, we need to specify _both_ the key-data class and set the right flag that provides the public-part of the cert/key (asymmetric) or the shared-key (symmetric) in order to be sure that with the given key, the given document has a valid signature.

In other words, to correctly verify a SAML XML document signed with HMAC, we need to invoke xmlsec1 with `--enabled-key-data hmac --hmackey keyfile`. The reason that removing the `--enabled-key-data` flag looks like a "fix", is because xmlsec1 is reading the embedded key within the SAML XML document (specifically, the `Signature` node should contain a `KeyInfo` node that contains a `KeyValue` node) and thus the you are relying on a key that is in the control of an external entity.

---

Could pysaml2 support hmac as the key-data class and method to correctly verify signatures? Yes, it could be done, but we need to refactor the verification process. As I said above, we now rely on finding the certificate on the metadata document of the issuer, and we specifically look for an x509 cert. This should be generalized to look for other types of key-data classes and then expect the same key-data classes on the received SAML document. We then invoke xmlsec1 with the right _pair_ of flags.
Is it a priority? I would say no, because I haven't seen anyone really using anything different than (self-signed) x509 certs. But, if you feel this is helpful and want to give it a try, I am looking forward to a PR ;) 

I hope this was clear and helpful. If you feel any of it is confusing or wrong, let me know.

**Comment by frcl** [comment]
Thank you very much for the extansive clarification.

I can see that removing the `--enabled-key-data` flag is unwise.

In my specific case x509 is used, but I have to use `--enabled-key-data x509` for it to work. (I'm not even sure what the difference to `raw-x509-cert`.) Also the cert is not self-signed. Instead it is signed by the CA cert of my university, which operates the IdP.

To clarify: This works (with `--insecure` flag necessary if CA cert is not installed, otherwise it fails with `msg=unable to get local issuer certificate`):
```
$ /usr/bin/xmlsec1 --verify --insecure --enabled-reference-uris empty,same-doc --enabled-key-data x509 --pubkey-cert-pem cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:assertion:Assertion --node-id … saml.xml
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
```
while this fails:
```
$ /usr/bin/xmlsec1 --verify --insecure --enabled-reference-uris empty,same-doc --enabled-key-data raw-x509-cert --pubkey-cert-pem cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:assertion:Assertion --node-id … saml.xml
func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=370:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
FAIL
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
```

If I understand this correctly the first version should be safe from man-in-middle attacks, right?

If so, does something speak against extending to `--enabled-key-data x509,raw-x509-cert` or making it an option?

**Comment by c00kiemon5ter** [comment]
> Also the cert is not self-signed. Instead it is signed by the CA cert of my university, which operates the IdP.
> 
> To clarify: This works (with `--insecure` flag necessary if CA cert is not installed, otherwise it fails with `msg=unable to get local issuer certificate`)

We do not care to verify that the certificate is trusted by the system/host, neither if it is self-signed or not. What we care is to verify that the given certificate is the one that is used to verify the signature in the given document. `--insecure` should not be needed, and no check against the system certificate store should take place.

> while this fails:
> 
> ```
> $ /usr/bin/xmlsec1 --verify --insecure --enabled-reference-uris empty,same-doc --enabled-key-data raw-x509-cert --pubkey-cert-pem cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:assertion:Assertion --node-id … saml.xml
> ```

`saml.xml` should contain (one or more) `X509Certificate` elements (XPath: `/samlp:Response/saml:Assertion/ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509Certificate`). One of those `X509Certificate` elements should contain the certificate that you should also have in `cert.pem`.
I can only assume that _this may not be the case_; ie, the given cert (`cert.pem`) is not right. `cert.pem` should be either the leaf certificate, or the fullchain (with the leaf certificate on the top, because actually only the first one will be read).
If that is the case it is possible that the IdP has updated its metadata and the metadata you use are stale (they contain an older certificate) - updating the metadata should just fix it.

**Comment by frcl** [comment]
Ok, I figured it out.

> If that is the case it is possible that the IdP has updated its metadata and the metadata you use are stale (they contain an older certificate) - updating the metadata should just fix it.

At first I was very confused because (automatically) updating the metadata is what *caused* the issue so. Actually I expected something to break because the IdP operator wrote me that they are changing the way they are signing certificates, but the error message about local issuer certificate send me on the wrong track.

Now I contacted the IdP operator about what you wrote here and it turns out that the IdP was misconfigured and everything I thought I understood was wong ¯\_(ツ)_/¯

Sorry for the fuss. As far as I'm concerned the problem is solved. No further action necassary.
