### ISSUE TITLE
Issue with adfs attribute namespace

### ISSUE THREAD

**Issue by sibo-git** [IdentityPython/pysaml2#948]
```xml
<ns1:Attribute Name="http://schemas.xmlsoap.org/claims/upn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified" FriendlyName="upn">
  <ns1:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">lvjw@contoso.com</ns1:AttributeValue>
</ns1:Attribute>
```

Name why not `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn`？

**Comment by c00kiemon5ter** [comment]
Hello @sibo-git ,

the attribute maps that pysaml2 defines for adfs are in conflict because of the same friendly names used across the different adfs versions.

Please, try the following:
1. create a folder and add a python file with this content
    ```py
    from saml2.attributemaps import adfs_v20
    
    MAP = adfs_v20.MAP
    ```
2. in your configuration set the [`attribute_map_dir` option](https://pysaml2.readthedocs.io/en/latest/howto/config.html#attribute-map-dir) to point to your folder.

This will separate the adfs v2 attributes from other versions and will allow pysaml2 to pick the right namespace.

**Comment by sibo-git** [comment]
> Hello @sibo-git ,
> 
> the attribute maps that pysaml2 defines for adfs are in conflict because of the same friendly names used across the different adfs versions.
> 
> Please, try the following:
> 
> 1. create a folder and add a python file with this content
>    ```python
>    from saml2.attributemaps import adfs_v20
>    
>    MAP = adfs_v20.MAP
>    ```
> 2. in your configuration set the [`attribute_map_dir` option](https://pysaml2.readthedocs.io/en/latest/howto/config.html#attribute-map-dir) to point to your folder.
> 
> This will separate the adfs v2 attributes from other versions and will allow pysaml2 to pick the right namespace.

great!!!!,thanks
